import path from "node:path";
import { AnalysisResult } from "../types/models.js";

/** Compact Markdown summary suitable for a CI / pull-request comment. */
export function renderSummary(result: AnalysisResult): string {
  const findingsById = new Map(result.findings.map((f) => [f.id, f]));
  const trend =
    result.trend.scoreDelta != null
      ? ` (${result.trend.scoreDelta > 0 ? "+" : ""}${result.trend.scoreDelta} vs previous)`
      : "";

  const top = result.topDebts
    .slice(0, 5)
    .map((d, i) => {
      const f = findingsById.get(d.findingId);
      const where = f ? path.basename(f.filePath) : "unknown";
      return `${i + 1}. **${f?.ruleName ?? d.findingId}** — ${f?.severity.toUpperCase() ?? ""} · effort ${d.effort} · \`${where}\``;
    })
    .join("\n");

  const quickWins = result.topDebts.filter((d) => {
    const f = findingsById.get(d.findingId);
    return (
      f &&
      (f.severity === "critical" || f.severity === "high") &&
      d.effort === "S"
    );
  }).length;

  return [
    `## 🔍 OrgLens Health Report`,
    "",
    `**Grade ${result.grade.letter} (${result.grade.label}) · Score ${result.score.overall}/100${trend}**`,
    "",
    `| Metric | Value |`,
    `| --- | --- |`,
    `| Total findings | ${result.findings.length} |`,
    `| Confidence | ${result.score.confidence}% |`,
    `| Quick wins (high sev, low effort) | ${quickWins} |`,
    `| Components mapped | ${result.graph.nodes.length} |`,
    "",
    `### Top priorities`,
    top || "_No prioritized findings._",
    "",
    `<sub>Generated by OrgLens · ${new Date(result.timestamp).toLocaleString()}</sub>`,
  ].join("\n");
}
